// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsAutoComplete")>]
[<assembly: AssemblyProductAttribute("FsAutoComplete")>]
[<assembly: AssemblyDescriptionAttribute("A command line tool for interfacing with FSharp.Compiler.Service over a pipe.")>]
[<assembly: AssemblyVersionAttribute("0.34.0")>]
[<assembly: AssemblyFileVersionAttribute("0.34.0")>]
[<assembly: AssemblyMetadataAttribute("githash","6d6e953b2928ca990adb6c773acde4d1c24ab7a8")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsAutoComplete"
    let [<Literal>] AssemblyProduct = "FsAutoComplete"
    let [<Literal>] AssemblyDescription = "A command line tool for interfacing with FSharp.Compiler.Service over a pipe."
    let [<Literal>] AssemblyVersion = "0.34.0"
    let [<Literal>] AssemblyFileVersion = "0.34.0"
    let [<Literal>] AssemblyMetadata_githash = "6d6e953b2928ca990adb6c773acde4d1c24ab7a8"
